# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16s_fhPvN2jj61GoGD6waNT4VyrO7HPKF
"""

def tashxis(belgi):
  if belgi=="istima":
    return "parasetamol iching"
  elif belgi == "bosh og'rig'i":
    return "bol nol iching"
  elif belgi == "tish o'grig'i":
    return "quepen iching"
  else:
      return "battar bo'ling 😂"
belgi=input("kasallik belgisini kiriting: ")
natija=tashxis(belgi)
print(natija)

def millat(belgi):
    if belgi in ["qora", "burni katta", "baland bo'yli", "jingalak", "kalta", "o'rilgan soch"]:
        return "Afrikalik"
    elif belgi in ["bug'doyrang", "burni o'rtacha", "o'rta bo'yli", "uzun sochli"]:
        return "O'rta Osiyolik"
    elif belgi in ["ko'zi qisiq", "oppoq", "ko'zoynakli", "tepakal", "o'rilgan soch"]:
        return "Sharqiy Osiyolik"
    elif belgi in ["qoracha", "o'rtas bo'yli", "rang barang", "jingalak", "uzun", "kalta", "o'rilgan soch", "burni kichik"]:
        return "Yevropalik"
    else:
        return "san o'zbek massan🤦‍♂️ san Xotoyliksan 🎎"

# Get the user input and call the function
belgi = input("Odam tavsifini kiriting: ")
natija = millat(belgi)

natija = millat(belgi)
print(natija)